option to add a custom prefix to all of Tailwind's generated utility classes
awssat/tailwindo pull request #30
Opened 2020-09-19 05:26 UTC by daryledesilva

example:
```
tailwindo path/to/directory/ --prefix=tw-
```

2020-09-19 14:28 UTC, abdumu requested changes
This a great addition to the tool. I would love to see a test even if it's one line to make sure it's not affecting the output.

Thanks

2020-09-19 14:28 UTC, abdumu commented on src/Converter.php
> +    protected $prefix = '';
If we are not allowing empty prefix, this could be a `null`

2020-09-19 14:28 UTC, abdumu commented on src/Converter.php
> +        $this->prefix = trim($prefix);
`if(! empty($prefix))  ... { .. }` ?

2020-09-19 14:28 UTC, abdumu commented on src/Converter.php
> +                    return $this->prefix ? trim(implode(' ', array_filter(array_map(function ($class) {
Use `if` conditions and multiple lines for readability. multiple functions in one line makes debugging harder.

2020-09-20 01:28 UTC, daryledesilva commented
> This a great addition to the tool. I would love to see a test even if it's one line to make sure it's not affecting the output.
> 
> Thanks

thanks! sorry for the test, i was in a hurry yesterday 😅 please check latest updates and let me know if there's anything else that needs to be done!

2020-09-20 01:28 UTC, daryledesilva commented
> This a great addition to the tool. I would love to see a test even if it's one line to make sure it's not affecting the output.
> 
> Thanks

@abdumu thanks! sorry for the test, i was in a hurry yesterday 😅 please check latest updates and let me know if there's anything else that needs to be done!

2020-09-20 15:47 UTC, merged

2020-09-20 15:47 UTC, abdumu commented
thanks

2020-10-28 12:20 UTC, serwin35 commented
does it work on the official version?

2020-10-28 13:30 UTC, daryledesilva commented
> does it work on the official version?
> 
> "The "--prefix" option does not exist."

i believe it's not in the latest release yet https://github.com/awssat/tailwindo/compare/3.0.2...master